### ISSUE TITLE
Bidirectional Connector: Provider/Consumer

### ISSUE THREAD

**Issue by gboege** [orchestracities/boost#17]
@gboege kinda rings a bell, but need to refresh my memory...

gb: It is what we have spoken about: 
Consumer: Send out request, receiving response
Provider: Receiving request, sending response
FIWARE CIM Connector has to be able to handle both, because reqests are incoming, notifications outgoing. 
So there is no only Provider or Consumer Connector

**Comment by c0c0n3** [comment]
implemented by PR #25 but notice shortcomings listed there.
see also about it: #24
