### ISSUE TITLE
Orion deployment in k8s Cloud

### ISSUE THREAD

**Issue by c0c0n3** [orchestracities/boost#5]
Replace dummy HttpBin with Orion. We're using HttpBin in our local Minikube deployment, we have to swap it out for Orion. @chicco785 has developed a number of Helm charts for Orchestra we can possibly use out of the box or just tweak a little.

@gboege Need to decide what FiWare components to bring in exactly.

**Comment by gboege** [comment]
I will do this with kompose in my Rancher Cloud
