### ISSUE TITLE
Create header-HTTP-Header content

### ISSUE THREAD

**Issue by gboege** [orchestracities/boost#7]
Remarks: 
- change to "header" from "dth-header" ... this is due to alignment with the standard
- value of header must be a quoted string with all doublequote escaped
- no spaces in the quoted string

Message-Type for Requests is "QueryMessage"
Message-Type for Responses is "ResultMessage"

**Comment by gboege** [comment]
a) Just adding the IDS header part from the multipart-messages as an additional header to the original HTTP Call (the content of the header-Header is matching the example from 4.4.2 2. QueryMessage):

The additional header-HTTP-Header follows the extension-header mechanism that allows additional entity-header fields to be defined without changing the protocol (https://www.rfc-editor.org/rfc/pdfrfc/rfc2616.txt.pdf - section 7.1). The value of the header-HTTP-Header must be formatted as a quoted-string containing qdtext escaping the forbidden " VCHAR to a quoted-pair \" (https://tools.ietf.org/html/rfc7230 - section 3.2.6).

![DemoCall plus header](https://user-images.githubusercontent.com/44926950/71022858-cc084780-2101-11ea-9e54-6541448d36de.png)

**Comment by gboege** [comment]
The creation of the content of the header-Header is pre-created in the ballerina script. 
It contains all steps to obtain the securityToken (first create own JWT and then obtain DAT from DAPS).
Explanations to the other fields are following soon. 
There are some unique IDs for reference,
some timestamps 
and some data to be parameterized during creation (modelVersion with Updates ca. each year and IssuerConnector individual for each connector).

**Comment by chicco785** [comment]
@gboege having a header containing JSON is not really optimal and raise several encoding issues. What's the rational?

**Comment by c0c0n3** [comment]
See #13

**Comment by gboege** [comment]
@chicco785 
The Data Transfer Header by definition MUST follow the IDSA Datamodel and must be serialized in JSON-LD...  If we want to put the Data Transfer Header info to the headers, this is consequence. 
Otherwise we would have to do any further transformations we wanted to avoid. 
And the escaping of doublequotes is allowed as mentioned in the reference.

**Comment by c0c0n3** [comment]
@gboege thanks for clarifying :-)

> Base64-encode the complete JSON string

This would make our life much easier. In fact, handling HTTP header values **correctly** has historically been a source of headaches for many before us. In particular, even Go built-in libs seem to have trouble with quoted values, e.g. something like `header: "{\"url\": \"http:\/\/golang\"}"`---see [comments](https://github.com/orchestracities/boost/issues/13#issuecomment-571533034) to #13. Also, if there's any escaping in the original JSON doc, we'd have to handle that too---which I'm not doing at the moment, just pushed my code to the `dev` branch, have a look at `orionadapter/sec/tokenrep.go`. 

So this looks like a slippery road downhill. Any chance we can push for the IDS header value to be Base 64 encoded e.g. a header value of

    {
        "@type": "ids:QueryMessage",
        "id": "http://industrialdataspace.org/queryMessage/1a421b8c-3407-44a8-aeb9-253f145c869a",
        "issued": "2019-10-25T15:35:34.589Z",
        "modelVersion": "2.1.0",
        "issuerConnector": "https://companyA.com/connector/59a68243-dd96-4c8d-88a9-0f0e03e13b1b",
        "securityToken": {
                "@type": "ids:DynamicAttributeToken",
                "tokenFormat": "https://w3id.org/idsa/code/tokenformat/JWT",
                "tokenValue": "my.fat.jws"
        }
    }

would be sent over the wire as

    header: ewoJIkB0eXBlIjogImlkczpRdWVyeU1lc3NhZ2UiLAoJImlkIjogImh0dHA6Ly9pbmR1c3RyaWFsZGF0YXNwYWNlLm9yZy9xdWVyeU1lc3NhZ2UvMWE0MjFiOGMtMzQwNy00NGE4LWFlYjktMjUzZjE0NWM4NjlhIiwKCSJpc3N1ZWQiOiAiMjAxOS0xMC0yNVQxNTozNTozNC41ODlaIiwKCSJtb2RlbFZlcnNpb24iOiAiMi4xLjAiLAoJImlzc3VlckNvbm5lY3RvciI6ICJodHRwczovL2NvbXBhbnlBLmNvbS9jb25uZWN0b3IvNTlhNjgyNDMtZGQ5Ni00YzhkLTg4YTktMGYwZTAzZTEzYjFiIiwKCSJzZWN1cml0eVRva2VuIjogewoJCSJAdHlwZSI6ICJpZHM6RHluYW1pY0F0dHJpYnV0ZVRva2VuIiwKCQkidG9rZW5Gb3JtYXQiOiAiaHR0cHM6Ly93M2lkLm9yZy9pZHNhL2NvZGUvdG9rZW5mb3JtYXQvSldUIiwKCQkidG9rZW5WYWx1ZSI6ICJteS5mYXQuandzIgoJfQp9

**Comment by gboege** [comment]
I will change the IDS documentation accordingly. Probably the much better way. Thanks for raising attention and making the solution better as a team.

**Comment by c0c0n3** [comment]
awe, rock on!

**Comment by gboege** [comment]
IDSA-Documents already changed: 
![image](https://user-images.githubusercontent.com/44926950/71905434-6c351780-3168-11ea-984d-0e4e3533932c.png)

**Comment by gboege** [comment]
The same of course for the signature part... and additionally mentioning UTF-8 as character Set.

Well done, and quick :-)

**Comment by c0c0n3** [comment]
implemented by #16.
